#!/bin/sh

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# This script depends on the "jq" package: dnf install jq

CONTAINER="trans-vpn"
PORT="9091"
BIND_MOUNT_PATH="/tmp"     #  Base path for bind mounts 

#  These directories and files need to exist before we can begin
[ -e ${BIND_MOUNT_PATH}/transmission ] || echo "${BIND_MOUNT_PATH}/transmission directory does not exist" && exit 1
[ -e ${BIND_MOUNT_PATH}/openvpn/openvpn.conf ] || echo "${BIND_MOUNT_PATH}/openvpn/openvpn.conf file does not exist" && exit 1
[ -e ${BIND_MOUNT_PATH}/log ] || echo "${BIND_MOUNT_PATH}/log directory does not exist" && exit 1

if [ "$1" == "run" ]; then
	#  Start the container running
	sudo podman run --detach --name=$CONTAINER --rm --volume=/tmp/transmission:/transmission --volume=/tmp/openvpn:/etc/openvpn/client --volume=/tmp/log:/var/log --cap-add=NET_ADMIN --device /dev/net/tun --publish=${PORT}:9091/tcp trans-vpn
	sleep 1
	#  Get the IP address that the container is using
	IP=$(sudo podman inspect $CONTAINER | jq -r '.[0].NetworkSettings.IPAddress')
	#  Set up the port forwarding configuration
	sudo firewall-cmd --zone=public --add-port ${PORT}/tcp
	sudo firewall-cmd --zone=trusted --add-masquerade
	sudo firewall-cmd --zone=trusted --add-forward-port=port=${PORT}:proto=tcp:toaddr=$IP
else
	#  Get the IP address that the container is using
	IP=$(sudo podman inspect $CONTAINER | jq -r '.[0].NetworkSettings.IPAddress')
	#  Stop the container
	sudo podman stop $CONTAINER
	#  Remove the port forwarding configuration
	sudo firewall-cmd --zone=trusted --remove-forward-port=port=${PORT}:proto=tcp:toaddr=$IP
	sudo firewall-cmd --zone=trusted --remove-masquerade
	sudo firewall-cmd --zone=public --remove-port ${PORT}/tcp
fi
